volumes:
  redis_data:
services:
  redis:
    container_name: redis
    image: docker.io/library/redis:alpine
    command: redis-server --save 30 1 --loglevel warning
    restart: always
    volumes:
      - redis_data:/data
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE
  haproxy:
    container_name: haproxy
    image: haproxy:latest
    restart: always
    ports:
        - "8404:8404"
        - "9050:9050"
    volumes:
        - ./haproxy:/usr/local/etc/haproxy
    depends_on: [tor]
  searxng:
    container_name: searxng
    restart: always
    image: searxng_local # docker.io/searxng/searxng:latest
    build:
      context: .
      dockerfile: ./Dockerfile.searxng
    volumes:
      - ./searxng:/etc/searxng
    ports:
      - 8080:8080
    depends_on: [redis, morty, tor]
    environment:
      - SEARXNG_BASE_URL=http://${SEARXNG_HOSTNAME:-searxng}:8080/
    #  - SEARXNG_DEBUG=1
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
  morty:
    container_name: morty
    image: ghcr.io/karmishin/morty:master
    restart: always
    command:
      - "-listen=0.0.0.0:3000"
      - "-socks5=socks5://haproxy:9050"
      - "-timeout=10"
    depends_on:
      - haproxy
    ports:
      - "3000:3000"
  tor:
    image: tor_local
    build:
      context: .
      dockerfile: ./Dockerfile.tor
    restart: always
    volumes: [./tor:/etc/tor]
    deploy:
      mode: replicated
      replicas: 9
