# see https://docs.searxng.org/admin/settings/settings.html#settings-use-default-settings
use_default_settings:
  engines:
    remove:
      - wolframalpha
      - soundcloud
      - qwant
      - qwant images
      - qwant news
      - qwant videos
      - openverse
      - wallhaven
      - library of congress
      - sepiasearch
      - genius
      - openairepublications
      - openairedatasets
      - internetarchivescholar
      - kickass
      - bt4g
      - solidtorrents
      - piratebay
      - z-library
      - bpb #( unexpected crash )
      - mojeek #( access denied )
      - presearch #( unexpected crash )
      - presearch images
      - presearch videos
      - presearch news
      - searchmysite #( access denied )
      - yep #( access denied )
      - yacy
      - tootfinder
server:
  bind_address: "0.0.0.0" # address to listen on
  # base_url is defined in the SEARXNG_BASE_URL environment variable, see .env and docker-compose.yml
  secret_key: "123456789"
  limiter: false # can be disabled for a private instance
  image_proxy: true
search:
  formats:
    - html
    - json
  # Filter results. 0: None, 1: Moderate, 2: Strict
  safe_search: 2
ui:
  static_use_hash: true
redis:
  url: redis://redis:6379/0
outgoing:
  request_timeout: 5.0
  max_request_timeout: 30.0
  proxies:
    "all://":
      - socks5h://tor0:9050
      - socks5h://tor1:9050
      - socks5h://tor2:9050
      - socks5h://tor3:9050
      - socks5h://tor4:9050
      - socks5h://tor5:9050
      - socks5h://tor6:9050
      - socks5h://tor7:9050
      - socks5h://tor8:9050
      - socks5h://tor9:9050
  retries: 3
  proxy_request_redundancy: 8
engines:
  - name: wikidata
    timeout: 10.0

  - name: piped
    engine: piped
    timeout: 5.0

    # URL to use as link and for embeds
    frontend_url: https://srv.piped.video
    # Instance will be selected randomly, for more see https://piped-instances.kavin.rocks/
    backend_url:
      - https://pipedapi-libre.kavin.rocks
      - https://pipedapi.adminforge.de
      - https://pipedapi.tokhmi.xyz
      - https://pipedapi.moomoo.me
      - https://pipedapi.syncpundit.io
      - https://api-piped.mha.fi
      - https://piped-api.garudalinux.org
      - https://pipedapi.rivo.lol
      - https://pipedapi.leptons.xyz
      - https://piped-api.lunar.icu
      - https://ytapi.dc09.ru
      - https://pipedapi.colinslegacy.com
      - https://yapi.vyper.me
      - https://api.looleh.xyz
      - https://piped-api.cfe.re
      - https://pipedapi.r4fo.com
      - https://pipedapi.darkness.services
      - https://pipedapi-libre.kavin.rocks
      - https://pa.mint.lgbt
      - https://pa.il.ax
      - https://piped-api.privacy.com.de
      - https://api.piped.projectsegfau.lt
      - https://pipedapi.in.projectsegfau.lt
      - https://pipedapi.us.projectsegfau.lt
      - https://watchapi.whatever.social
      - https://api.piped.privacydev.net
      - https://pipedapi.palveluntarjoaja.eu
      - https://pipedapi.smnz.de
      - https://pipedapi.adminforge.de
      - https://pipedapi.qdi.fi
      - https://piped-api.hostux.net
      - https://pdapi.vern.cc
      - https://pipedapi.pfcd.me
      - https://pipedapi.frontendfriendly.xyz
      - https://api.piped.yt
      - https://pipedapi.astartes.nl
      - https://pipedapi.osphost.fi
      - https://pipedapi.simpleprivacy.fr
      - https://pipedapi.drgns.space
      - https://piapi.ggtyler.dev
      - https://api.watch.pluto.lat
      - https://piped-backend.seitan-ayoub.lol
      - https://pipedapi.owo.si
      - https://api.piped.minionflo.net
      - https://pipedapi.nezumi.party
      - https://pipedapi.ducks.party
      - https://pipedapi.ngn.tf
      - https://pipedapi.coldforge.xyz
      - https://piped-api.codespace.cz
      - https://pipedapi.reallyaweso.me
      - https://pipedapi.phoenixthrush.com
      - https://api.piped.private.coffee
      - https://schaunapi.ehwurscht.at
      - https://pipedapi.dedyn.io
